### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by JoyceBabu** [vortarian/serverless-sqs-fifo#1]
When I install the plugin with 
```
npm install --save https://github.com/vortarian/serverless-sqs-fifo
```

I am getting the error
> Serverless plugin "serverless-sqs-fifo" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

**Comment by JoyceBabu** [comment]
It is working when `serverless` is also installed locally. With global `serverless` it is failing with due to unmet module dependency

```
{ Error: Cannot find module 'serverless/lib/plugins/aws/lib/validate'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joyce/Projects/serverless/logs-ennexa-com/nodejs/node_modules/serverless-sqs-fifo/index.js:4:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at plugins.forEach.error (/Users/joyce/.nvm/versions/node/v6.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:70:24)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/Users/joyce/.nvm/versions/node/v6.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:68:13)
    at PluginManager.loadServicePlugins (/Users/joyce/.nvm/versions/node/v6.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:109:10)
    at PluginManager.loadAllPlugins (/Users/joyce/.nvm/versions/node/v6.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:64:10)
    at service.load.then (/Users/joyce/.nvm/versions/node/v6.11.2/lib/node_modules/serverless/lib/Serverless.js:64:28) code: 'MODULE_NOT_FOUND' }

```
